//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpHorizons.Settings.Interpretation.Ephemeris {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class DefaultEphemerisInterpretationSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DefaultEphemerisInterpretationSettings defaultInstance = ((DefaultEphemerisInterpretationSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DefaultEphemerisInterpretationSettings())));
        
        public static DefaultEphemerisInterpretationSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ephemeris")]
        public string EphemerisDataStart {
            get {
                return ((string)(this["EphemerisDataStart"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int EphemerisDataBlockCount {
            get {
                return ((int)(this["EphemerisDataBlockCount"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("West-longitude positive")]
        public string WestPositiveLongitude {
            get {
                return ((string)(this["WestPositiveLongitude"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("East-longitude positive")]
        public string EastPositiveLongitude {
            get {
                return ((string)(this["EastPositiveLongitude"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B.C.")]
        public string BoundaryEpochBCE {
            get {
                return ((string)(this["BoundaryEpochBCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C.E.")]
        public string BoundaryEpochCE {
            get {
                return ((string)(this["BoundaryEpochCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Start time")]
        public string StartEpoch {
            get {
                return ((string)(this["StartEpoch"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Stop  time")]
        public string StopEpoch {
            get {
                return ((string)(this["StopEpoch"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Start time")]
        public string TimeSystem {
            get {
                return ((string)(this["TimeSystem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Start time")]
        public string TimeZoneOffset {
            get {
                return ((string)(this["TimeZoneOffset"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Step-size")]
        public string StepSize {
            get {
                return ((string)(this["StepSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reference frame")]
        public string ReferenceSystem {
            get {
                return ((string)(this["ReferenceSystem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$$SOE")]
        public string StartOfEphemeris {
            get {
                return ((string)(this["StartOfEphemeris"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$$EOE")]
        public string EndOfEphemeris {
            get {
                return ((string)(this["EndOfEphemeris"]));
            }
        }
    }
}
