//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpHorizons.Interpretation.Ephemeris.Origin {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class DefaultOriginInterpretationKeys : global::System.Configuration.ApplicationSettingsBase {
        
        private static DefaultOriginInterpretationKeys defaultInstance = ((DefaultOriginInterpretationKeys)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DefaultOriginInterpretationKeys())));
        
        public static DefaultOriginInterpretationKeys Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center body name")]
        public string BodyName {
            get {
                return ((string)(this["BodyName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center geodetic")]
        public string GeodeticCoordinate {
            get {
                return ((string)(this["GeodeticCoordinate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center cylindric")]
        public string CylindricalCoordinate {
            get {
                return ((string)(this["CylindricalCoordinate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center pole/equ")]
        public string ReferenceEllipsoid {
            get {
                return ((string)(this["ReferenceEllipsoid"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center radii")]
        public string Radii {
            get {
                return ((string)(this["Radii"]));
            }
        }
    }
}
