//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpHorizons.Interpretation.Ephemeris {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class DefaultEphemerisInterpretation : global::System.Configuration.ApplicationSettingsBase {
        
        private static DefaultEphemerisInterpretation defaultInstance = ((DefaultEphemerisInterpretation)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DefaultEphemerisInterpretation())));
        
        public static DefaultEphemerisInterpretation Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ephemeris")]
        public string EphemerisDataStart {
            get {
                return ((string)(this["EphemerisDataStart"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int EphemerisDataBlockCount {
            get {
                return ((int)(this["EphemerisDataBlockCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("West-longitude positive")]
        public string WestPositiveLongitude {
            get {
                return ((string)(this["WestPositiveLongitude"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("East-longitude positive")]
        public string EastPositiveLongitude {
            get {
                return ((string)(this["EastPositiveLongitude"]));
            }
        }
    }
}
