name: nuget
on:
  release:
    types: [published]
jobs:
  nuget:
    name: NuGet Publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 7.0.x 
      - name: Get Release
        uses: robinraju/release-downloader@v1.7
        with:
          tag: ${{ env.GITHUB_REF }}
      - name: Push NuGet.org
        shell : bash
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          for file in *.nupkg; do
              dotnet nuget push "$file" -source "https://api.nuget.org/v3/index.json" -k "$NUGET_API_KEY"
          done
      - name: Push GitHub Packages
        shell : bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          for file in *.nupkg; do
              dotnet nuget push "$file" -source "https://nuget.pkg.github.com/ErikWe/index.json" -k "$GITHUB_TOKEN"
          done